services:
  psm:
    build: .
    user: reflex
    hostname: psm
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "8000:8000"
    env_file:
      - path: .env
        required: false
    volumes:
      - psm-db:/app/data

volumes:
  psm-db:
