PLEXAPI_AUTH_SERVER_TOKEN = "Plex API Token"
PLEXAPI_AUTH_SERVER_BASEURL = "http://plex.yourdomain.com:32400"
SECTION_EXPIRED = "Expired"
DEFAULT_EXPIRY_DAYS = 30
ENABLE_ALL_TASKS = false
ENABLE_UPDATE_STATUS_TASK = false
ENABLE_DISABLE_EXPIRED_USERS_TASK = false
ALLOW_SYNC = true
LOG_LEVEL = "WARNING"
